### ISSUE TITLE
RFE: List available providers

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/broker#41]
I think it would be great if one could get a list of available providers:

`broker provider --list`

**Comment by JacobCallahan** [comment]
I can think of two different paths this could go.

1: Add this information under the `nick-help` subcommand. This could look like `broker nick-help --providers`
2: Create a `provider` subcommand and roll nick-help functionality under that as well.
```
broker provider --list                                     # list all available providers
broker provider AnsibleTower --actions       # list all actions for a provider (workflow)
broker provider AnsibleTower --workflows   # list all available workflows for AnsibleTower
broker provider AnsibleTower --workflow jenkins-test #list all available arguments for the workflow
```
Option 1  might be a little unclear as nicks are only linked to a provider by their actions. However, it is an established sub-command that is pretty clear about how it works.
Option 2 gives the user more information about providers while also maintaining the ability to get information about their actions.

**Comment by omaciel** [comment]
I like option `2` as it is more intuitive.

**Comment by JacobCallahan** [comment]
@SatelliteQE/quality-engineers I'd like your input on this as well.

**Comment by JacobCallahan** [comment]
@bherrin3 the provider context would only apply for this specific subcommand. all others will work as they currently do.

**Comment by kedark3** [comment]
How about just saying `broker provider` and it also tells you the current provider.

**Comment by JacobCallahan** [comment]
@kedark3 without adding some kind of context tracking system, broker can't know which provider you've used last.

**Comment by JacobCallahan** [comment]
Slight change to how option 2 will work since I want this command to be a more dynamic and overall better experience.

Notice in this demo how the providers (AnsibleTower and OpenShift) are now subcommands of the providers subcommand. Additionally, their actions are made apparent through their command options.

The biggest user experience win here is that actions for one provider aren't shown in the overall help text. So a user won't think they can use `--workflows` for anything other than `AnsibleTower`.

This also makes it easier when adding new providers/actions, since it will populate the subcommands/options based on the information in broker.py.
![ezgif-7-b16993000f48](https://user-images.githubusercontent.com/6618303/93393116-e9f50b00-f83f-11ea-953c-864669397330.gif)

@omaciel what do you think about this version?

**Comment by omaciel** [comment]
It looks great @JacobCallahan and still intuitive :)
