### ISSUE TITLE
Reconsider the name?

### ISSUE THREAD

**Issue by ironfroggy** [SatelliteQE/broker#6]
I'd like to suggest that some alternate names for this project be considered...

Reason 1: "broker" is a very generic name, it really does not advertise what the project is.
Reason 2: There are already lots of projects with nearly or exactly the same name, including a "broker" package on PyPI so we won't be able to publish this.

Initial suggestions to consider:
- machine-factory
- vmfactory
- boxfactory

**Comment by dsesami** [comment]
I like the premise, but I feel like the word "factory" for anything that isn't actually creating the objects isn't quite right? I might be being a stickler though.

We're checking out vms and checking them back in, so maybe a librarian joke could be made 😄 . That is also potentially too show-offy without being useful, though. 

vmfactory is simple and works. (librarian is a fun name though...)

**Comment by JacobCallahan** [comment]
@dsesami you're correct with the factory naming not being appropriate since broker doesn't do any actual work. It is a people person, it is good with talking to people! 
All kidding aside, librarian was one of the early naming concepts, but it was a bit long for my taste.
If a rename is in order, VMBroker/vmBroker/VMbroker could be considerations.

**Comment by mshriver** [comment]
@JacobCallahan with the focus on brokering provider workflows that give you a resource (maybe a VM), what about `HostBroker`

**Comment by lpramuk** [comment]
https://pypi.org/project/broker/

Broker made it to pypi as `broker`  (old unmaintained project was removed)
