### ISSUE TITLE
Support for custom vm provisioning templateas

### ISSUE THREAD

**Issue by dsesami** [SatelliteQE/broker#8]
It would be cool if a user could add a custom way of checking out a vm type. They would define it in a dictionary of sorts and put it in, and then they could arbitrarily add their providers that way.

**Comment by kedark3** [comment]
@dsesami can you provide an example of this? That'll help clarify the idea.

**Comment by dsesami** [comment]
@kedark3 sure. 

Let's say that someone using this system has an in-house method of procuring VMs. They likely have a bash script where they pass in parameters to allocate a VM and do other basic operations. They also use broker to manage VMs, though, so they'd like to not have to jump between different kinds of workflows to get a VM. So they simply define how to get a VM from that provider with some kind of basic templating, plug it in once, and can then use broker for all their providers.

**Comment by JacobCallahan** [comment]
@dsesami you could theoretically do that now. Create a provider (called whatever you think is most appropriate (I'm not good at names!!)) that accepts parameters from the VMBroker class, uses that to call your script (subprocess?), and pulls the information from that output to eventually construct a Host object for broker.

Definitely do-able, but would likely be pretty focused on how your script operates.

*broker is not liable for damages caused by external scripts*
